import { Shop } from "./shop";

export const shop:Shop = [
  ["woda","L"],
  ["mokre chustki","listków",72,"https://barbora.pl/produkty/home-care-chusteczki-nawilzane-classic-72-szt"],
  ["papier toaletowy","rolka",8,"https://barbora.pl/produkty/foxy-jedwab-papier-toaletowy-3-warstwy-8-rolek"],
  ["płyn do mycia naczyń","ml"],
  ["worki na śmieci","szt",20,"https://barbora.pl/produkty/stella-worki-na-smieci-hdld-z-uszami-wytrz-20-szt-60-l"],
  ["apap/ibuprom","tabletki"],
  ["helsi / Porost Islandzki / isla","tabletki"],
  ["reni","tabletki"],
  ["kiełbasa ~15cm","szt",4,"https://barbora.pl/produkty/morliny-kie-basa-g-ogowska-z-szynki-540-g"],
  ["mięso mielone wołowe","g",400,"https://barbora.pl/produkty/ukow-mieso-mielone-z-opatki-400-g"],
  ["mięso na gulasz","g",500,"https://barbora.pl/produkty/ukow-gulasz-wo-owy-500-g"],
  ["pierś kurczaka","g", 700,"https://barbora.pl/produkty/polski-drob-udo-bez-kosci-b-s-z-kurczaka-map-700-g"],
  ["polędwiczki wieprzowe","g"],
  ["sucha krakowka","g",100,"https://barbora.pl/produkty/drobimex-kie-basa-krakowska-drobiowa-100-g"],
  ["wędzony boczek","g"],
  ["żeberka surowe","g"],
  ["żeberka wędzone","g"],
  ["masło","g"],
  ["mleko","L"],
  ["ser żółty (krojony)","g"],
  ["smietana UHT 18%","g"],
  ["podłużne bułki do currywurst","szt"],
  ["tortilla","szt"],
  ["cebulka prażona","g"],
  ["kukurydza puszka","g"],
  ["makaron spagetti","g"],
  ["makaron tagliatelle","g"],
  ["mąka","g"],
  ["ogórki konserwowe","g"],
  ["olej rzepakowy","ml"],
  ["pomidory krojone puszka / przecier pomidorowy","g"],
  ["rum do grogu","L"],
  ["suszone śliwki","g"],
  ["zakwasu żytniego do żurku","ml"],
  ["żurawina","g"],
  ["majeranek","opakowanie"],
  ["oregano","opakowanie"],
  ["pieprz","g"],
  ["proszek do pieczenia","g"],
  ["sól","g"],
  ["ziarna jałowca","opakowanie"],
  ["zioła prowansalskie","opakowanie"],
  ["marchew","kg"],
  ["natka pietruszki","szt"],
  ["pieczarki","g"],
  ["pomidory","szt"],
  ["suchego grochu łuskanego (połówki)","g"],
  ["ziemniaki","kg"],
  ["bułka kajzerka","szt",1,"https://barbora.pl/produkty/otrebusy-bu-ka-kajzerka-55-g"],
  ["cebula","g",1000,"https://barbora.pl/produkty/cebula-kg"],
  ["chilli","opakowanie",1,"https://barbora.pl/produkty/prymat-papryka-ostra-20-g"],
  ["chleb biały krojony","kromki",20,"https://barbora.pl/produkty/putka-chleb-zwyk-y-krojony-500-g"],
  ["chocopuffs","g",250,"https://barbora.pl/produkty/nestle-p-atki-chocapic-250-g"],
  ["cini minis","g",250,"https://barbora.pl/produkty/nestle-p-atki-cini-minis-250-g"],
  ["cukier","g",500,"https://barbora.pl/produkty/polski-cukier-cukier-trzcinowy-demerara-500-g"],
  ["curry/kurkuma","g",20,"https://megasam24.pl/pl/p/Curry-Kamis-20g/351"],
  ["cytryna","g",1000,"https://barbora.pl/produkty/cytryna-kg"],
  ["czekolada gożka","tabliczki",1,"https://barbora.pl/produkty/wedel-czekolada-gorzka-90-g-100-g"],
  ["czerwona fasola puszka","g",400,"https://barbora.pl/produkty/home-garden-fasola-czerwona-400-g"],
  ["czerwona papryka","g",1000,"https://barbora.pl/produkty/papryka-czerwona-kg"],
  ["czosnek granulowany","g",20,"https://barbora.pl/produkty/prymat-czosnek-granulowany-20-g"],
  ["goździki","g",9,"https://barbora.pl/produkty/kamis-gozdziki-9-g"],
  ["jajka","sztuki",10,"https://barbora.pl/produkty/polskie-fermy-jaja-l-scio-kowe-10-szt"],
  ["jalapenos","g",340,"https://barbora.pl/produkty/casa-de-mexico-papryka-zielona-jalapeno-krojona-340-g"],
  ["kabanosy chili","opakowania",1,"https://barbora.pl/produkty/tarczynski-kabanos-exclusive-chili-105-g"],
  ["kapusta kiszona","g",500,"https://barbora.pl/produkty/dominik-kapusta-kiszona-folia-500-g"],
  ["kapusty (główka)","g",1000,"https://barbora.pl/produkty/kapusta-bia-a-kg"],
  ["karkówka","g",560,"https://barbora.pl/produkty/ukow-karkowka-bez-kosci-na-kotlety-560-g"],
  ["kasza gryczana","g",500,"https://barbora.pl/produkty/eureko-kasza-gryczana-palona-bio-500-g"],
  ["kawa","g",250,"https://barbora.pl/produkty/jacobs-kronung-kawa-mielona-250-g"],
  ["ketchup ostry","g",480,"https://barbora.pl/produkty/pudliszki-ketchup-pikantny-480-g"],
];
