import { Shop } from "./shop";

export const megasam24: Shop = [
  ["apap/ibuprom", "tabletki",],
  ["bułka kajzerka", "szt", 1, "https://megasam24.pl/pl/p/Kajzerka-55g/1784"],
  ["cebula", "g", 1000, "https://megasam24.pl/pl/p/Cebula-1kg-siatka/1953"],
  ["cebulka prażona", "g",],
  ["chilli", "opakowanie", 1, "https://megasam24.pl/pl/p/Papryka-ostra-mielona-Prymat-20-g/4998"],
  ["chleb biały krojony", "kromki", 20, "https://megasam24.pl/pl/p/Chleb-zwykly-krojony-Putka-500g/1765"],
  ["chocopuffs", "g", 250, "https://megasam24.pl/pl/p/Mlekolaki-Choco-Muszelki-Zbozowe-muszelki-o-smaku-czekoladowym-Lubella-250-g/4741"],
  ["cini minis", "g", 250, "https://megasam24.pl/pl/p/Platki-sniadaniowe-Cini-Minis-Nestle-250g/78"],
  ["cukier", "g", 500, "https://megasam24.pl/pl/p/Cukier-brazowy-Diamant-500-g/4548"],
  ["curry/kurkuma", "g", 20, "https://megasam24.pl/pl/p/Kurkuma-mielona-Prymat-20-g/4977"],
  ["czekolada gożka", "tabliczki", 1, "https://megasam24.pl/pl/p/Czekolada-gorzka-E.-Wedel-100g/892"],
  ["czerwona fasola puszka", "g", 400, "https://megasam24.pl/pl/p/Fasola-czerwona-konserwowa-Dawtona-400g/3381"],
  ["czerwona papryka", "g", 500, "https://megasam24.pl/pl/p/Papryka-slodka-czerwona-500g-2-szt./1982"],
  ["czosnek granulowany", "g", 20, "https://megasam24.pl/pl/p/Czosnek-suszony-Prymat-20-g/5010"],
  ["goździki", "g", 10, "https://megasam24.pl/pl/p/Gozdziki-Prymat-10-g/4965"],
  ["helsi / Porost Islandzki / isla", "tabletki",],
  ["jajka", "sztuki", 10, "https://megasam24.pl/pl/p/Jaja-z-chowu-na-wolnym-wybiegu-kl.L-z-Sokolowa-Oldar-10szt./1573"],
  ["jalapenos", "g", 340, "https://megasam24.pl/pl/p/Papryka-jalapeno-zielona-krojona-Casa-de-Mexico-340g/647"],
  ["kabanosy chili", "opakowania", 1, "https://megasam24.pl/pl/p/Kabanos-exclusive-dojrzewajacy-Tarczynski-90g-/1438"],
  ["kapusta kiszona", "g", 1000, "https://megasam24.pl/pl/p/Kapusta-kiszona-surowkowa-Pawlowski-i-Synowie-1-kg-wiaderko/4680"],
  ["kapusty (główka)", "g", 2000, "https://megasam24.pl/pl/p/Kapusta-biala-2-3-kg-1-szt./1964"],
  ["karkówka", "g", 1400, "https://megasam24.pl/pl/p/Mieso-Karkowka-wieprzowa-bez-kosci-pelna-z-wagi-1%2C4-kg-/1658"],
  ["kasza gryczana", "g", 900, "https://megasam24.pl/pl/p/Kasza-gryczana-prazona-Melvit-900g-/7036"],
  ["kawa", "g", 250, "https://megasam24.pl/pl/p/Kawa-mielona-Intermezzo-palona-Segafredo-250g/862"],
  ["ketchup ostry", "g", 480, "https://megasam24.pl/pl/p/Ketchup-pikantny-Pudliszki-480g/458"],
  ["kiełbasa ~15cm", "szt", 3, "https://megasam24.pl/pl/p/Kielbasa-slaska-Sokolow-280g-/1401"],
  ["kukurydza puszka", "g", 400, "https://megasam24.pl/pl/p/Kukurydza-konserwowa-Pudliszki-400g/582"],
  ["majeranek", "opakowanie", 1, "https://megasam24.pl/pl/p/Majeranek-Prymat-8-g/4982"],
  ["makaron spagetti", "g", 500, "https://megasam24.pl/pl/p/Makaron-spaghetti-Lubella-500g/100"],
  ["makaron tagliatelle", "g", 500, "https://megasam24.pl/pl/p/Makaron-tagliatelle-Primo-Gusto-500g/109"],
  ["marchew", "kg", 1, "https://megasam24.pl/pl/p/Marchew-1kg-paczkowana/1973"],
  ["mięso mielone wołowe", "g", 500, "https://megasam24.pl/pl/p/Mieso-mielone-wolowe-extra-ok.-0%2C5-kg/7194"],
  ["mięso na gulasz", "g", 600, "https://megasam24.pl/pl/p/Mieso-Gulasz-wolowy-z-wagi-0%2C6kg/1742"],
  ["mleko", "L", 1, "https://megasam24.pl/pl/p/Mleko-UHT-3%2C2-Mlekovita-1l/1345"],
  ["mokre chustki", "listków", 42, "https://megasam24.pl/pl/p/Nawilzany-papier-toaletowy-Velvet-Rumianek-i-Aloes-42szt./10180"],
  ["mąka", "g", 1000, "https://megasam24.pl/pl/p/Maka-pszenna-Poznanska-1kg-/42"],
  ["natka pietruszki", "szt", 1, "https://megasam24.pl/pl/p/Natka-pietruszki-peczek-1-szt./1986"],
  ["ogórki konserwowe", "g", 900, "https://megasam24.pl/pl/p/Ogorki-konserwowe-luksusowe-produkt-pasteryzowany-Dawtona-900g/626"],
  ["olej rzepakowy", "ml", 1000, "https://megasam24.pl/pl/p/Olej-rzepakowy-rafinowany-Popularny-1l/261"],
  ["oregano", "opakowanie", 1, "https://megasam24.pl/pl/p/Oregano-Prymat-8-g/4985"],
  ["papier toaletowy", "rolka", 8, "https://megasam24.pl/pl/p/Papier-toaletowy-Mola-Familijna-bialy-8-szt./2510"],
  ["pieczarki", "g", 500, "https://megasam24.pl/pl/p/Pieczarka-biala-500g-paczkowana/1985"],
  ["pieprz", "g", 20, "https://megasam24.pl/pl/p/Pieprz-czarny-mielony-Kamis-20g/339"],
  ["pierś kurczaka", "g", 1000, "https://megasam24.pl/pl/p/Mieso-z-uda-kurczaka-Miesne-Specjaly-z-wagi-1kg-/1626"],
  ["podłużne bułki do currywurst", "szt", 1, "https://megasam24.pl/pl/p/Bagielino-wieloziarniste-110g/10593"],
  ["polędwiczki wieprzowe", "g",],
  ["pomidory", "szt", 2, "https://megasam24.pl/pl/p/Pomidor-okragly-czerwony-500g-2-3-szt./1991"],
  ["pomidory krojone puszka / przecier pomidorowy", "g", 500, "https://megasam24.pl/pl/p/Przecier-pomidorowy-Primo-Gusto-500g/794"],
  ["proszek do pieczenia", "g", 30, "https://megasam24.pl/pl/p/Proszek-do-pieczenia-Gellwe-30g/5297"],
  ["płyn do mycia naczyń", "ml", 450, "https://megasam24.pl/pl/p/Plyn-do-mycia-naczyn-Ludwik-cytryna-450g/2428"],
  ["reni", "tabletki",],
  ["rum do grogu", "L",],
  ["ser żółty (krojony)", "g", 150, "https://megasam24.pl/pl/p/Ser-zolty-plastry-Gouda-Mlekovita-150g/953"],
  ["smietana UHT 18%", "g", 500, "https://megasam24.pl/pl/p/Smietanka-18-Laciata-UHT-Mlekpol-500ml/1561"],
  ["sucha krakowka", "g", 1000, "https://megasam24.pl/pl/p/Kielbasa-krakowska-pieczona-sucha-Olewnik-ok.-1kg-/5953"],
  ["suchego grochu łuskanego (połówki)", "g", 400, "https://megasam24.pl/pl/p/Groch-luskany-polowki-Melvit-400g/4781"],
  ["suszone śliwki", "g", 200, "https://megasam24.pl/pl/p/Sliwki-cale-owoce-Bakalland-200g/509"],
  ["sól", "g", 600, "https://megasam24.pl/pl/p/Sol-himalajska-drobnoziarnista-jodowana-OSole-600-g/4636"],
  ["tortilla", "szt", 18, "https://megasam24.pl/pl/p/Tortilla-pszenna-Sandra-18szt./1825"],
  ["worki na śmieci", "szt", 20, "https://megasam24.pl/pl/p/Worki-na-smieci-60l-Jan-Niezbedny-20-szt./2579"],
  ["wędzony boczek", "g", 400, "https://megasam24.pl/pl/p/Boczek-krolewski-wedzony-Duda-z-wagi-0%2C4kg-/1522"],
  ["zakwasu żytniego do żurku", "ml", 370, "https://megasam24.pl/pl/p/Zurek-na-zakwasie-koncentrat-Rolnik-370ml/1156"],
  ["ziarna jałowca", "opakowanie", 1, "https://megasam24.pl/pl/p/Owoc-jalowca-Prymat-15-g/4988"],
  ["ziemniaki", "kg", 2.5, "https://megasam24.pl/pl/p/Ziemniak-jadalny-myty-2%2C5kg-paczkowany/2007"],
  ["zioła prowansalskie", "opakowanie", 1, "https://megasam24.pl/pl/p/Ziola-prowansalskie-suszone-Prymat-10-g/4499"],
  ["żeberka surowe", "g", 600, "https://megasam24.pl/pl/p/Mieso-Zeberka-wieprzowe-extra-paski-z-wagi-0%2C6kg-/1667"],
  ["żeberka wędzone", "g",],
  ["żurawina", "g", 300, "https://megasam24.pl/pl/p/Zurawina-cala-Rolnik-300g-/5293"],
];
